### ISSUE TITLE
ImportError: /home/afm_cvpr2019-master/lib/afm_op/CUDA.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd

### ISSUE THREAD

**Issue by JanineCHEN** [cherubicXN/afm_cvpr2019#20]
Hi, I have run into this following error when trying to execute `python test.py --config-file experiments/afm_atrous.yaml --gpu 0`:

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from modeling.afm import AFM
  File "/home/afm_cvpr2019-master/modeling/afm.py", line 3, in <module>
    from dataset.build import build_train_dataset, build_test_dataset
  File "/home/afm_cvpr2019-master/dataset/build.py", line 3, in <module>
    from .afmDataset import AFMTrainDataset, AFMTestDataset, collect_fn
  File "/home/afm_cvpr2019-master/dataset/afmDataset.py", line 10, in <module>
    from .cache import AfmTrainCache
  File "/home/afm_cvpr2019-master/dataset/cache.py", line 6, in <module>
    from lib.afm_op import afm
  File "/home/afm_cvpr2019-master/lib/afm_op/__init__.py", line 2, in <module>
    from .CUDA import afm
ImportError: /home/afm_cvpr2019-master/lib/afm_op/CUDA.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd
```
I have followed the INSTALL.md without errors.

Any idea why this happens? Thank you in advance!

**Comment by JanineCHEN** [comment]
FYI, the following are my execution details with make and develop following INSTALL.md:

```
(afm) user:~/afm_cvpr2019-master$ cd lib
(afm) user:~/afm_cvpr2019-master/lib$ make
cd afm_op; python setup.py build_ext --inplace; rm -rf build; cd ../../
/home/anaconda3/envs/afm/lib/python3.6/distutils/extension.py:131: UserWarning: Unknown Extension options: 'defined_macros'
  warnings.warn(msg)
running build_ext
building 'CUDA' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/cuda
gcc -pthread -B /home/anaconda3/envs/afm/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I. -I/home/anaconda3/envs/afm/lib/python3.6/site-packages/torch/include -I/home/anaconda3/envs/afm/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/anaconda3/envs/afm/lib/python3.6/site-packages/torch/include/TH -I/home/anaconda3/envs/afm/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/anaconda3/envs/afm/include/python3.6m -c ./vision.cpp -o build/temp.linux-x86_64-3.6/./vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=CUDA -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -I. -I/home/anaconda3/envs/afm/lib/python3.6/site-packages/torch/include -I/home/anaconda3/envs/afm/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/anaconda3/envs/afm/lib/python3.6/site-packages/torch/include/TH -I/home/anaconda3/envs/afm/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/anaconda3/envs/afm/include/python3.6m -c ./cuda/afm.cu -o build/temp.linux-x86_64-3.6/./cuda/afm.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=CUDA -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
creating build/lib.linux-x86_64-3.6
g++ -pthread -shared -B /home/anaconda3/envs/afm/compiler_compat -L/home/anaconda3/envs/afm/lib -Wl,-rpath=/home/anaconda3/envs/afm/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/./vision.o build/temp.linux-x86_64-3.6/./cuda/afm.o -L/usr/local/cuda/lib64 -lcudart -o build/lib.linux-x86_64-3.6/CUDA.cpython-36m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.6/CUDA.cpython-36m-x86_64-linux-gnu.so -> 
cd squeeze/; python setup.py build_ext --inplace; rm -rf build; cd ../../
running build_ext
skipping 'squeeze.cpp' Cython extension (up-to-date)
building 'squeeze' extension
creating build
creating build/temp.linux-x86_64-3.6
gcc -pthread -B /home/anaconda3/envs/afm/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/anaconda3/envs/afm/lib/python3.6/site-packages/numpy/core/include -I/home/anaconda3/envs/afm/include/python3.6m -c kernel.cpp -o build/temp.linux-x86_64-3.6/kernel.o -Wno-unused-function
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
kernel.cpp: In function ‘void region_grow(int, int, float, float&, std::vector<Point>&, std::vector<Point>&, std::vector<float>&, PoLsMap&, float)’:
kernel.cpp:132:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int id = 0; id < map(x,y).size(); ++id) {
                     ~~~^~~~~~~~~~~~~~~~~
kernel.cpp:154:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0; i < reg_int.size(); ++i)
                    ~~^~~~~~~~~~~~~~~~
kernel.cpp:164:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for(int k = 0; k < map(xx,yy).size(); ++k) {
                                ~~^~~~~~~~~~~~~~~~~~~
kernel.cpp: In function ‘bool region2rect(const std::vector<Point>&, const std::vector<float>&, float, float, float, Rectangle&)’:
kernel.cpp:199:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i=0; i<reg_int.size(); ++i)
                  ~^~~~~~~~~~~~~~~
kernel.cpp:218:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i=0; i<reg_int.size(); ++i)
                  ~^~~~~~~~~~~~~~~
kernel.cpp: In function ‘void refine(std::vector<Point>&, Rectangle&, std::vector<float>&, PoLsMap&)’:
kernel.cpp:277:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0; i < reg_int.size(); ++i)
                    ~~^~~~~~~~~~~~~~~~
kernel.cpp:291:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0; i < reg_rot.size(); ++i)
                    ~~^~~~~~~~~~~~~~~~
kernel.cpp:312:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for(int i = 0; i < local_ind.size();++i)
                        ~~^~~~~~~~~~~~~~~~~~
kernel.cpp:317:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(int n = 0; n < map(x,y).size();++n)
                            ~~^~~~~~~~~~~~~~~~~
kernel.cpp:267:11: warning: unused variable ‘x1’ [-Wunused-variable]
     float x1 = rect.l_min*dx - rect.w_min*dy;
           ^~
kernel.cpp:268:11: warning: unused variable ‘y1’ [-Wunused-variable]
     float y1 = rect.l_min*dy + rect.w_min*dx;
           ^~
kernel.cpp:269:11: warning: unused variable ‘x2’ [-Wunused-variable]
     float x2 = rect.l_max*dx - rect.w_min*dy;
           ^~
kernel.cpp:270:11: warning: unused variable ‘y2’ [-Wunused-variable]
     float y2 = rect.l_max*dy + rect.w_min*dx;
           ^~
kernel.cpp:271:11: warning: unused variable ‘x3’ [-Wunused-variable]
     float x3 = rect.l_max*dx - rect.w_max*dy;
           ^~
kernel.cpp:272:11: warning: unused variable ‘y3’ [-Wunused-variable]
     float y3 = rect.l_max*dy + rect.w_max*dx;
           ^~
kernel.cpp:273:11: warning: unused variable ‘x4’ [-Wunused-variable]
     float x4 = rect.l_min*dx - rect.w_max*dy;
           ^~
kernel.cpp:274:11: warning: unused variable ‘y4’ [-Wunused-variable]
     float y4 = rect.l_min*dy + rect.w_max*dx;
           ^~
kernel.cpp: In function ‘void _region_grow(int, int, const float*, const float*, const float*, int, float*, int*)’:
kernel.cpp:364:15: warning: unused variable ‘length’ [-Wunused-variable]
         float length = sqrt((vec_rects[i].x1-vec_rects[i].x2)*(vec_rects[i].x1-vec_rects[i].x2) +
               ^~~~~~
gcc -pthread -B /home/anaconda3/envs/afm/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/anaconda3/envs/afm/lib/python3.6/site-packages/numpy/core/include -I/home/anaconda3/envs/afm/include/python3.6m -c squeeze.cpp -o build/temp.linux-x86_64-3.6/squeeze.o -Wno-unused-function
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/anaconda3/envs/afm/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                 from /home/anaconda3/envs/afm/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/anaconda3/envs/afm/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from squeeze.cpp:581:
/home/anaconda3/envs/afm/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
g++ -pthread -shared -B /home/anaconda3/envs/afm/compiler_compat -L/home/anaconda3/envs/afm/lib -Wl,-rpath=/home/anaconda3/envs/afm/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/kernel.o build/temp.linux-x86_64-3.6/squeeze.o -o /home/afm_cvpr2019-master/lib/squeeze/squeeze.cpython-36m-x86_64-linux-gnu.so
(afm) user:~/afm_cvpr2019-master/lib$ conda develop . ./lib
added /home/.local/share/Trash/files/lib
completed operation for: /home/.local/share/Trash/files/lib
added /home/.local/share/Trash/files/lib/lib
completed operation for: /home/.local/share/Trash/files/lib/lib
```

**Comment by cherubicXN** [comment]
Did you check your CUDA version?

**Comment by JanineCHEN** [comment]
> Did you check your CUDA version?

Hi, thank you for responding. My CUDA version is 10.1

**Comment by JanineCHEN** [comment]
Hi, I changed the code as following to fit my CUDA version:

```
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
```
It works now

**Comment by JanineCHEN** [comment]
As a follow up, I got this output after executing `python test.py --config-file experiments/afm_atrous.yaml --gpu 0`

![image](https://user-images.githubusercontent.com/37527041/87122904-57bd0d80-c2b8-11ea-9d61-11ebf0982f51.png)
